class FlightAware::Api
  def initialize
    @api_key = ENV["FLIGHT_AWARE_API_KEY"] || ""
  end

  def get_owner(ident)
    {
      "owner": {
        "name": "UNITED AIRLINES INC",
        "location": "CHICAGO IL",
        "location2": "233 S WACKER DR",
        "website": "null"
      }
    }
  end

  def get_aircraft(type)
    {
      "manufacturer": "Boeing",
      "type": "777-200",
      "description": "twin-jet",
      "engine_count": 2,
      "engine_type": "jet"
    }
  end

  def get_flights(ident)
    {
      "flights": [
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "null",
          "actual_runway_on": "null",
          "fa_flight_id": "UAL4-1723298769-fa-2617p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78001",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1723283126-fa-1285p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 0,
          "arrival_delay": 0,
          "filed_ete": 35700,
          "foresight_predictions_available": false,
          "scheduled_out": "2024-08-13T12:40:00Z",
          "estimated_out": "2024-08-13T12:40:00Z",
          "actual_out": "null",
          "scheduled_off": "2024-08-13T12:50:00Z",
          "estimated_off": "2024-08-13T12:50:00Z",
          "actual_off": "null",
          "scheduled_on": "2024-08-13T22:45:00Z",
          "estimated_on": "2024-08-13T22:45:00Z",
          "actual_on": "null",
          "scheduled_in": "2024-08-13T22:55:00Z",
          "estimated_in": "2024-08-13T22:55:00Z",
          "actual_in": "null",
          "progress_percent": 0,
          "status": "Scheduled",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 424,
          "filed_altitude": "null",
          "route": "null",
          "baggage_claim": "null",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "null",
          "gate_destination": "null",
          "terminal_origin": "null",
          "terminal_destination": "null",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "null",
          "actual_runway_on": "null",
          "fa_flight_id": "UAL4-1723266918-fa-1561p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78001",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1723253291-airline-169p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 0,
          "arrival_delay": 0,
          "filed_ete": 35700,
          "foresight_predictions_available": false,
          "scheduled_out": "2024-08-12T12:40:00Z",
          "estimated_out": "2024-08-12T12:40:00Z",
          "actual_out": "null",
          "scheduled_off": "2024-08-12T12:50:00Z",
          "estimated_off": "2024-08-12T12:50:00Z",
          "actual_off": "null",
          "scheduled_on": "2024-08-12T22:45:00Z",
          "estimated_on": "2024-08-12T22:45:00Z",
          "actual_on": "null",
          "scheduled_in": "2024-08-12T22:55:00Z",
          "estimated_in": "2024-08-12T22:55:00Z",
          "actual_in": "null",
          "progress_percent": 0,
          "status": "Scheduled",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 424,
          "filed_altitude": "null",
          "route": "null",
          "baggage_claim": "null",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "null",
          "gate_destination": "null",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "null",
          "actual_runway_on": "null",
          "fa_flight_id": "UAL4-1723177856-fa-1671p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N27015",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1723109622-fa-749p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 0,
          "arrival_delay": 120,
          "filed_ete": 34920,
          "foresight_predictions_available": false,
          "scheduled_out": "2024-08-11T12:40:00Z",
          "estimated_out": "2024-08-11T12:40:00Z",
          "actual_out": "null",
          "scheduled_off": "2024-08-11T12:50:00Z",
          "estimated_off": "2024-08-11T13:05:00Z",
          "actual_off": "null",
          "scheduled_on": "2024-08-11T22:32:00Z",
          "estimated_on": "2024-08-11T22:47:00Z",
          "actual_on": "null",
          "scheduled_in": "2024-08-11T22:55:00Z",
          "estimated_in": "2024-08-11T22:57:00Z",
          "actual_in": "null",
          "progress_percent": 0,
          "status": "Scheduled",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 481,
          "filed_altitude": 360,
          "route": "SEGAN DLH J21 GEP MCI TUL J87 CVE GUSHR3",
          "baggage_claim": "F12",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "null",
          "gate_destination": "E4",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27R",
          "actual_runway_on": "08L",
          "fa_flight_id": "UAL4-1723109622-fa-764p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78008",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1723080697-airline-545p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 480,
          "arrival_delay": -240,
          "filed_ete": 34920,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-10T12:40:00Z",
          "estimated_out": "2024-08-10T12:40:00Z",
          "actual_out": "2024-08-10T12:48:00Z",
          "scheduled_off": "2024-08-10T12:50:00Z",
          "estimated_off": "2024-08-10T13:00:00Z",
          "actual_off": "2024-08-10T13:00:00Z",
          "scheduled_on": "2024-08-10T22:32:00Z",
          "estimated_on": "2024-08-10T22:42:26Z",
          "actual_on": "2024-08-10T22:42:26Z",
          "scheduled_in": "2024-08-10T22:55:00Z",
          "estimated_in": "2024-08-10T22:52:11Z",
          "actual_in": "2024-08-10T22:51:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 360,
          "route": "5007N/07729W STL J101 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B49",
          "gate_destination": "E5",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27R",
          "actual_runway_on": "08L",
          "fa_flight_id": "UAL4-1723034703-schedule-632p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78017",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722938796-fa-1892p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 120,
          "arrival_delay": 300,
          "filed_ete": 35580,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-09T12:40:00Z",
          "estimated_out": "2024-08-09T12:40:00Z",
          "actual_out": "2024-08-09T12:42:00Z",
          "scheduled_off": "2024-08-09T12:50:00Z",
          "estimated_off": "2024-08-09T13:07:24Z",
          "actual_off": "2024-08-09T13:07:24Z",
          "scheduled_on": "2024-08-09T22:43:00Z",
          "estimated_on": "2024-08-09T22:53:00Z",
          "actual_on": "2024-08-09T22:53:00Z",
          "scheduled_in": "2024-08-09T22:55:00Z",
          "estimated_in": "2024-08-09T23:03:00Z",
          "actual_in": "2024-08-09T23:00:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 496,
          "filed_altitude": 340,
          "route": "5724N/06251W SSM STL J101 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B33",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27L",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722866911-fa-1779p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N69020",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1722851822-fa-44p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 4320,
          "arrival_delay": 3120,
          "filed_ete": 34380,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-08T12:40:00Z",
          "estimated_out": "2024-08-08T13:37:00Z",
          "actual_out": "2024-08-08T13:52:00Z",
          "scheduled_off": "2024-08-08T12:50:00Z",
          "estimated_off": "2024-08-08T14:19:16Z",
          "actual_off": "2024-08-08T14:19:16Z",
          "scheduled_on": "2024-08-08T22:23:00Z",
          "estimated_on": "2024-08-08T23:43:19Z",
          "actual_on": "2024-08-08T23:43:19Z",
          "scheduled_in": "2024-08-08T22:55:00Z",
          "estimated_in": "2024-08-08T23:53:00Z",
          "actual_in": "2024-08-08T23:47:00Z",
          "progress_percent": 100,
          "status": "Arrived / Delayed",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 481,
          "filed_altitude": 360,
          "route": "TADIS MCW MCI TUL J87 CVE GUSHR3",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B31",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27R",
          "actual_runway_on": "26L",
          "fa_flight_id": "UAL4-1722861793-airline-1410p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N27015",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722764846-fa-567p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 300,
          "arrival_delay": -960,
          "filed_ete": 33720,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-07T12:40:00Z",
          "estimated_out": "2024-08-07T12:50:00Z",
          "actual_out": "2024-08-07T12:45:00Z",
          "scheduled_off": "2024-08-07T12:50:00Z",
          "estimated_off": "2024-08-07T13:06:06Z",
          "actual_off": "2024-08-07T13:05:00Z",
          "scheduled_on": "2024-08-07T22:12:00Z",
          "estimated_on": "2024-08-07T22:29:40Z",
          "actual_on": "2024-08-07T22:29:40Z",
          "scheduled_in": "2024-08-07T22:55:00Z",
          "estimated_in": "2024-08-07T22:39:00Z",
          "actual_in": "2024-08-07T22:39:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B49",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27R",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722775390-airline-465p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N69020",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722677611-fa-739p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 840,
          "arrival_delay": -180,
          "filed_ete": 33720,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-06T12:40:00Z",
          "estimated_out": "2024-08-06T12:40:00Z",
          "actual_out": "2024-08-06T12:54:00Z",
          "scheduled_off": "2024-08-06T12:50:00Z",
          "estimated_off": "2024-08-06T13:20:36Z",
          "actual_off": "2024-08-06T13:20:36Z",
          "scheduled_on": "2024-08-06T22:12:00Z",
          "estimated_on": "2024-08-06T22:48:00Z",
          "actual_on": "2024-08-06T22:48:00Z",
          "scheduled_in": "2024-08-06T22:55:00Z",
          "estimated_in": "2024-08-06T22:57:42Z",
          "actual_in": "2024-08-06T22:52:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B38",
          "gate_destination": "E4",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27R",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722677608-fa-623p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N27015",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722652066-airline-944p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 600,
          "arrival_delay": -360,
          "filed_ete": 33960,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-05T12:40:00Z",
          "estimated_out": "2024-08-05T12:55:00Z",
          "actual_out": "2024-08-05T12:50:00Z",
          "scheduled_off": "2024-08-05T12:50:00Z",
          "estimated_off": "2024-08-05T13:36:59Z",
          "actual_off": "2024-08-05T13:36:59Z",
          "scheduled_on": "2024-08-05T22:16:00Z",
          "estimated_on": "2024-08-05T22:46:06Z",
          "actual_on": "2024-08-05T22:46:06Z",
          "scheduled_in": "2024-08-05T22:55:00Z",
          "estimated_in": "2024-08-05T22:58:00Z",
          "actual_in": "2024-08-05T22:49:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B33",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27L",
          "actual_runway_on": "08L",
          "fa_flight_id": "UAL4-1722590840-fa-1028p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N77019",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722504694-fa-1017p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 180,
          "arrival_delay": -540,
          "filed_ete": 34500,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-04T12:40:00Z",
          "estimated_out": "2024-08-04T12:40:00Z",
          "actual_out": "2024-08-04T12:43:00Z",
          "scheduled_off": "2024-08-04T12:50:00Z",
          "estimated_off": "2024-08-04T13:06:00Z",
          "actual_off": "2024-08-04T13:04:48Z",
          "scheduled_on": "2024-08-04T22:25:00Z",
          "estimated_on": "2024-08-04T22:35:56Z",
          "actual_on": "2024-08-04T22:35:56Z",
          "scheduled_in": "2024-08-04T22:55:00Z",
          "estimated_in": "2024-08-04T22:45:00Z",
          "actual_in": "2024-08-04T22:46:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F9",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B31",
          "gate_destination": "E5",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27L",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722504683-fa-1274p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78008",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722419730-fa-232p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 240,
          "arrival_delay": 1380,
          "filed_ete": 33780,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-03T12:40:00Z",
          "estimated_out": "2024-08-03T12:40:00Z",
          "actual_out": "2024-08-03T12:44:00Z",
          "scheduled_off": "2024-08-03T12:50:00Z",
          "estimated_off": "2024-08-03T13:09:00Z",
          "actual_off": "2024-08-03T12:58:00Z",
          "scheduled_on": "2024-08-03T22:13:00Z",
          "estimated_on": "2024-08-03T22:57:00Z",
          "actual_on": "2024-08-03T22:57:00Z",
          "scheduled_in": "2024-08-03T22:55:00Z",
          "estimated_in": "2024-08-03T23:18:00Z",
          "actual_in": "2024-08-03T23:18:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B48",
          "gate_destination": "E5",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "27L",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722429950-airline-1573p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78001",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL5-1722333263-fa-2457p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 2280,
          "arrival_delay": 1680,
          "filed_ete": 33840,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-02T12:40:00Z",
          "estimated_out": "2024-08-02T13:15:00Z",
          "actual_out": "2024-08-02T13:18:00Z",
          "scheduled_off": "2024-08-02T12:50:00Z",
          "estimated_off": "2024-08-02T13:56:00Z",
          "actual_off": "2024-08-02T13:54:51Z",
          "scheduled_on": "2024-08-02T22:14:00Z",
          "estimated_on": "2024-08-02T23:19:17Z",
          "actual_on": "2024-08-02T23:19:17Z",
          "scheduled_in": "2024-08-02T22:55:00Z",
          "estimated_in": "2024-08-02T23:28:00Z",
          "actual_in": "2024-08-02T23:23:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B43",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "09R",
          "actual_runway_on": "26L",
          "fa_flight_id": "UAL4-1722333261-fa-1293p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N78001",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722246512-fa-16p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 3360,
          "arrival_delay": 3540,
          "filed_ete": 34020,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-08-01T12:40:00Z",
          "estimated_out": "2024-08-01T12:40:00Z",
          "actual_out": "2024-08-01T13:36:00Z",
          "scheduled_off": "2024-08-01T12:50:00Z",
          "estimated_off": "2024-08-01T14:16:00Z",
          "actual_off": "2024-08-01T14:00:00Z",
          "scheduled_on": "2024-08-01T22:17:00Z",
          "estimated_on": "2024-08-01T23:45:00Z",
          "actual_on": "2024-08-01T23:45:00Z",
          "scheduled_in": "2024-08-01T22:55:00Z",
          "estimated_in": "2024-08-01T23:52:00Z",
          "actual_in": "2024-08-01T23:54:00Z",
          "progress_percent": 100,
          "status": "Arrived / Delayed",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 500,
          "filed_altitude": 380,
          "route": "4517N/08213W FAM J137 LIT J180 SWB ZEEKK2",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B42",
          "gate_destination": "E7",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "09R",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722181447-fa-1441p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N79011",
          "atc_ident": "null",
          "inbound_fa_flight_id": "UAL924-1722181447-fa-1446p",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 180,
          "arrival_delay": -120,
          "filed_ete": 33720,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-07-31T12:40:00Z",
          "estimated_out": "2024-07-31T12:40:00Z",
          "actual_out": "2024-07-31T12:43:00Z",
          "scheduled_off": "2024-07-31T12:50:00Z",
          "estimated_off": "2024-07-31T13:23:00Z",
          "actual_off": "2024-07-31T13:22:30Z",
          "scheduled_on": "2024-07-31T22:12:00Z",
          "estimated_on": "2024-07-31T22:50:22Z",
          "actual_on": "2024-07-31T22:50:22Z",
          "scheduled_in": "2024-07-31T22:55:00Z",
          "estimated_in": "2024-07-31T22:57:00Z",
          "actual_in": "2024-07-31T22:53:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 499,
          "filed_altitude": 360,
          "route": "VANSI TVC OBK J101 LIT J180 SWB GESNR1",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B49",
          "gate_destination": "E4",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        },
        {
          "ident": "UAL4",
          "ident_icao": "UAL4",
          "ident_iata": "UA4",
          "actual_runway_off": "09R",
          "actual_runway_on": "27",
          "fa_flight_id": "UAL4-1722158540-fa-2356p",
          "operator": "UAL",
          "operator_icao": "UAL",
          "operator_iata": "UA",
          "flight_number": "4",
          "registration": "N795UA",
          "atc_ident": "null",
          "inbound_fa_flight_id": "null",
          "codeshares": [
            "AUA7813",
            "BEL9080",
            "DLH7621",
            "SWR3038",
            "ACA3913"
          ],
          "codeshares_iata": [
            "OS7813",
            "SN9080",
            "LH7621",
            "LX3038",
            "AC3913"
          ],
          "blocked": false,
          "diverted": false,
          "cancelled": false,
          "position_only": false,
          "origin": {
            "code": "EGLL",
            "code_icao": "EGLL",
            "code_iata": "LHR",
            "code_lid": "null",
            "timezone": "Europe/London",
            "name": "London Heathrow",
            "city": "London",
            "airport_info_url": "/airports/EGLL"
          },
          "destination": {
            "code": "KIAH",
            "code_icao": "KIAH",
            "code_iata": "IAH",
            "code_lid": "IAH",
            "timezone": "America/Chicago",
            "name": "Houston Bush Int'ctl",
            "city": "Houston",
            "airport_info_url": "/airports/KIAH"
          },
          "departure_delay": 480,
          "arrival_delay": -420,
          "filed_ete": 34440,
          "foresight_predictions_available": true,
          "scheduled_out": "2024-07-30T12:40:00Z",
          "estimated_out": "2024-07-30T12:40:00Z",
          "actual_out": "2024-07-30T12:48:00Z",
          "scheduled_off": "2024-07-30T12:50:00Z",
          "estimated_off": "2024-07-30T13:13:00Z",
          "actual_off": "2024-07-30T13:12:47Z",
          "scheduled_on": "2024-07-30T22:24:00Z",
          "estimated_on": "2024-07-30T22:43:21Z",
          "actual_on": "2024-07-30T22:43:21Z",
          "scheduled_in": "2024-07-30T22:55:00Z",
          "estimated_in": "2024-07-30T22:50:00Z",
          "actual_in": "2024-07-30T22:48:00Z",
          "progress_percent": 100,
          "status": "Arrived / Gate Arrival",
          "aircraft_type": "B772",
          "route_distance": 4829,
          "filed_airspeed": 499,
          "filed_altitude": 360,
          "route": "VANSI TVC OBK J101 LIT J180 SWB GESNR1",
          "baggage_claim": "F4",
          "seats_cabin_business": 24,
          "seats_cabin_coach": "null",
          "seats_cabin_first": 50,
          "gate_origin": "B33",
          "gate_destination": "E4",
          "terminal_origin": "2",
          "terminal_destination": "E",
          "type": "Airline"
        }
      ],
      "links": "null",
      "num_pages": 1
    }
  end
end